name: 'Edit JSON'
description: 'Github action to modify json files by properties.'
inputs:
  filename:
    description: 'Path to json file'
    required: true
  key:
    description: 'Property path in json file, e.g "name", "version", "scripts.build"'
    required: true
  value:
    description: 'Value for the specified property.'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'