name: 'Edito Json'
description: 'Github action to modify json file'
inputs:
  filename:
    description: 'Path to json file'
    required: true
  key:
    description: 'Property within json file, e.g "name", "version", "scripts.build"'
    required: true
  value:
    description: 'Value for specified property.'
    required: true
runs:
  using: 'node12'
  main: 'lib/index.js'